'use client';

import Navbar from "../components/Navbar";
import AuthGuard from "../components/AuthGuard";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "../components/ui/accordion";
import { Info } from "lucide-react";
import Leaderboard from "../components/Leaderboard";

export default function RewardsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <Navbar />
      <AuthGuard>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-28 pb-12 animate-in fade-in slide-in-from-bottom-2 duration-300">
          <div className="glass-panel p-8 rounded-2xl mb-8">
            <h1 className="text-4xl font-extrabold mb-2 bg-linear-to-r from-primary to-purple-400 bg-clip-text text-transparent">Rewards</h1>
            <p className="text-muted-foreground">Monitor your performance and rank and earnings</p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
            <div className="lg:col-span-2">
              <Leaderboard />
            </div>
            <div className="lg:col-span-1">
              <div className="glass-panel p-6 rounded-xl h-full flex flex-col justify-center items-center text-center">
                <h2 className="text-lg font-medium text-muted-foreground mb-2">Your Rank</h2>
                <div className="text-5xl font-extrabold text-primary mb-2">#42</div>
                <p className="text-sm text-muted-foreground">Top 5% of contributors</p>
              </div>
            </div>
          </div>

          <div className="mt-8">
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="calculation" className="border-border">
                <AccordionTrigger className="text-lg font-semibold">
                  <div className="flex items-center gap-2">
                    <Info className="h-5 w-5 text-primary" />
                    How are rewards calculated?
                  </div>
                </AccordionTrigger>
                <AccordionContent className="text-base text-muted-foreground space-y-4">
                  <p>Rewards are based on your project&apos;s position on the leaderboard. Your ranking is determined by impact and activity, including:</p>
                  <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li>Development activity from project contributors</li>
                    <li>Transactions and fees generated by your project</li>
                    <li>Downloads of your project&apos;s npm packages</li>
                  </ul>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </AuthGuard>
    </main>
  );
}
