changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: "⛓ Contract"
      labels:
        - "contract"
    - title: "🌐 Frontend"
      labels:
        - "frontend"
    - title: "📖 Docs"
      labels:
        - "docs"
    - title: "⚙️ Ops & CI"
      labels:
        - "ops"
    - title: "⚠️ Breaking Changes"
      labels:
        - "breaking"
    - title: "Other Changes"
      labels:
        - "*"
